FROM ros:humble-ros-base

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ros-humble-ros2bag \
       ros-humble-rosbag2-storage-mcap \
       ros-humble-sensor-msgs \
       ros-humble-nav-msgs \
       ros-humble-audio-common-msgs \
    && rm -rf /var/lib/apt/lists/*

CMD ["ros2", "bag", "play", "/bags/bag"]
